// i18n, дефолт RU (как в проде). t(lang).key
export const STRINGS = {
  ru: {
    brand: 'SIMILIS.AI', langBtn: 'EN',
    demoBadge: 'Static Demo · {n} объектов · прод-метрики в Дашборде',
    tabSearch: 'Поиск', tabDash: 'Дашборд',
    searchParams: 'Параметры поиска', queryTitle: 'Искомый предмет',
    pickPreset: 'Выбрать пример', uploadHint: 'Загрузка своего изображения доступна в Production API',
    presetModalTitle: 'Выберите пример находки', presetModalHint: 'В демо поиск идёт по 5 подготовленным примерам (в проде — загрузка своего фото).',
    preproc: 'Препроцессинг', tags: 'Теги поиска', domain: 'Культурный домен', prodOnly: 'Доступно в Production API',
    threshold: 'Порог схожести', model: 'Модель нейросети', provider: 'Поставщик данных', allProviders: 'Искать везде',
    found: 'Найдено', showMore: 'Показать ещё', favorites: 'Избранное', favEmpty: 'Отметьте находки звёздочкой — появятся здесь.',
    emptyTitle: 'Слишком строгий фильтр', emptyHint: 'Понизьте порог схожести или расширьте поставщика данных.',
    cardOwner: 'владелец', similarity: 'схожесть',
    modalTitle: 'Информация об артефакте',
    fCode: 'Шифр', fName: 'Наименование', fMaterial: 'Материал', fDesc: 'Описание', fSize: 'Размер',
    fSquare: 'Квадрат', fObject: 'Объект', fExc: 'Раскоп', fDating: 'Датировка', fSite: 'Памятник', fOwner: 'Владелец данных',
    map: 'География находок', similarHere: 'Похожие объекты',
    dashProdTitle: 'Продакшен SIMILIS (факт)', dashDemoTitle: 'Локальное демо (этот датасет)',
    kArtifacts: 'изображений', kSites: 'памятников', kModels: 'модели', kRecall: 'Recall@20', kTTFR: 'TTFR', kHITL: 'HITL rate',
    kDemoItems: 'артефактов', kDemoSites: 'памятников', kDemoOwners: 'владельца',
    chartTypes: 'Распределение типов (демо)', chartSites: 'Объекты по памятникам (демо)',
    honesty: 'Изображения и метаданные — реальные (ИИМК РАН, НовГУ). Similarity в демо — офлайн-прокси прод-эмбеддингов ResNet50/CLIP (иллюстрация); прод-метрики — факт проекта. Данные НовГУ: portal.novsu.ru/archeology.',
    loading: 'Загрузка данных…',
  },
  en: {
    brand: 'SIMILIS.AI', langBtn: 'RU',
    demoBadge: 'Static Demo · {n} items · prod metrics in Dashboard',
    tabSearch: 'Search', tabDash: 'Dashboard',
    searchParams: 'Search parameters', queryTitle: 'Query item',
    pickPreset: 'Pick an example', uploadHint: 'Uploading your own image is available in the Production API',
    presetModalTitle: 'Pick a query example', presetModalHint: 'The demo searches over 5 prepared examples (production allows uploading your own photo).',
    preproc: 'Preprocessing', tags: 'Search tags', domain: 'Cultural domain', prodOnly: 'Available in Production API',
    threshold: 'Similarity threshold', model: 'Neural model', provider: 'Data provider', allProviders: 'Search everywhere',
    found: 'Found', showMore: 'Show more', favorites: 'Favorites', favEmpty: 'Star artifacts to collect them here.',
    emptyTitle: 'Filter too strict', emptyHint: 'Lower the similarity threshold or widen the data provider.',
    cardOwner: 'owner', similarity: 'similarity',
    modalTitle: 'Artifact information',
    fCode: 'Code', fName: 'Name', fMaterial: 'Material', fDesc: 'Description', fSize: 'Size',
    fSquare: 'Square', fObject: 'Object', fExc: 'Excavation', fDating: 'Dating', fSite: 'Site', fOwner: 'Data owner',
    map: 'Find geography', similarHere: 'Similar objects',
    dashProdTitle: 'Production SIMILIS (fact)', dashDemoTitle: 'Local demo (this dataset)',
    kArtifacts: 'images', kSites: 'sites', kModels: 'models', kRecall: 'Recall@20', kTTFR: 'TTFR', kHITL: 'HITL rate',
    kDemoItems: 'artifacts', kDemoSites: 'sites', kDemoOwners: 'owners',
    chartTypes: 'Type distribution (demo)', chartSites: 'Objects by site (demo)',
    honesty: 'Images and metadata are real (IIMK RAS, NovSU). Demo similarity is an offline proxy of the production ResNet50/CLIP embeddings (illustrative); prod metrics are project facts. NovSU data: portal.novsu.ru/archeology.',
    loading: 'Loading data…',
  },
}
export const t = (lang) => STRINGS[lang] || STRINGS.ru
